// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZmBlIDblUqj7_WPb4YnkPixb_Sidr72w',
    appId: '1:1091822484217:web:d62b846de8f36022024028',
    messagingSenderId: '1091822484217',
    projectId: 'arogya-mitra-98929',
    authDomain: 'arogya-mitra-98929.firebaseapp.com',
    storageBucket: 'arogya-mitra-98929.firebasestorage.app',
    measurementId: 'G-JDBG2T5R0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAulhGuKv25vMN1x4qtnFbDMRvv-a_rMbA',
    appId: '1:1091822484217:android:7c450dbeff38593f024028',
    messagingSenderId: '1091822484217',
    projectId: 'arogya-mitra-98929',
    storageBucket: 'arogya-mitra-98929.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa32t-22iD50hHct3vWHDviaI1u-b58p8',
    appId: '1:1091822484217:ios:866dd8262b1aa030024028',
    messagingSenderId: '1091822484217',
    projectId: 'arogya-mitra-98929',
    storageBucket: 'arogya-mitra-98929.firebasestorage.app',
    iosBundleId: 'com.example.arogyaMitraDoctor',
  );
}
